### PR TITLE
Add TypeScript Support

### PR DESCRIPTION
**Pull request by philliphoff**
Enables the use of TypeScript within the `glimpse.agent` package (only, for now).  TypeScript files are transpiled and copied to the package's `release` folder, along with all of the existing JavaScript files.  The package is then 'run' from the `release` folder.  (I first tried to keep the generated files next to their respective TypeScript files, but it's simply unworkable from a source code control perspective until we have completely moved to TypeScript.)

The TypeScript compiler targets ES5 which *should* be what we want. Source maps are generated so that you can step between TypeScript code (when used) and JavaScript (when not).  The root installation task was updated to also install the TypeScript Definition (TSD) files needed to build the package.

One 'sample' inspector was refactored to show how TypeScript can be used and mixed with JavaScript.

### CODE REVIEW

**Comment by philliphoff** [comment]
This PR relates to #10.

**Comment by avanderhoorn** [comment]
Looks good to me. :shipit:

**Comment by avanderhoorn** [comment]
I'm currently getting the following "semantic" errors when I do the build:
```
➜  glimpse.agent git:(master) ✗ gulp build
[18:39:37] Using gulpfile ~/Projects/Glimpse.Node.Prototype/src/glimpse.agent/gulpfile.js
[18:39:37] Starting 'build-typescript'...
[18:39:37] Starting 'build-javascript'...
inspectors/environment-inspector.ts(3,49): error TS2307: Cannot find module 'http'.
inspectors/environment-inspector.ts(8,14): error TS2304: Cannot find name 'require'.
inspectors/environment-inspector.ts(9,10): error TS2304: Cannot find name 'require'.
inspectors/environment-inspector.ts(10,15): error TS2304: Cannot find name 'require'.
inspectors/inspector.ts(1,49): error TS2307: Cannot find module 'http'.
[18:39:38] TypeScript: 5 semantic errors
[18:39:38] TypeScript: emit succeeded (with errors)
[18:39:38] Finished 'build-typescript' after 1.56 s
[18:39:38] Finished 'build-javascript' after 1.54 s
[18:39:38] Starting 'build'...
[18:39:38] Finished 'build' after 44 μs
```

I thought adjusting the config to include `moduleResolution` would address the issue, but it didn't. Any ideas?
```
{
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"moduleResolution": "node"
	},
	"exclude": [
		"node_modules"
	]
}
```

**Comment by philliphoff** [comment]
Did you (globally) install TSD and do a `gulp install` from the root directory or a `tsd install` from the glimpse.agent directory?  It sounds like the type definitions for built-in node types haven't been installed.

**Pull request merged**
