### PR TITLE
Added TypeScript linting (i.e. TSLint) to build process

### PR DESCRIPTION
**Pull request by philliphoff**
Includes TSLint-based TypeScript listing to the build process (again, only to glimpse.agent at this point).  As the TypeScript codebase is currently very small and there are relatively fewer linting rules than for JavaScript, I've enabled nearly every rule.  If we find that too restrictive we can relax the rules as needed.

### CODE REVIEW

**Comment by philliphoff** [comment]
Related to #10 and #20.

**Comment by avanderhoorn** [comment]
How are you finding the two linters are working? My thought would be that they compliment each other, has that proved out?

**Comment by philliphoff** [comment]
The linters are completely separate, in that one operates solely on JavaScript files (ESLint) and the other solely on TypeScript files (TSLint) so they certainly do not interfere with each other.  They have many analogous rules (e.g. whether to use tabs or spaces, whitespace before/between/after constructs, etc.).  TSLint doesn't seem as mature (rule-wise) as ESLint so over time we may have to fix-up the codebase as new patterns/rules are established/implemented.

If and when we move completely to TypeScript then it would make sense to ditch ESLint.

**Comment by avanderhoorn** [comment]
Great, this is what I thought but wanted to confirm. In time we will most likely totally migrate over, but this is great for now. :shipit:

**Pull request merged**
