### PR TITLE
Add Skeleton Build Infrastructure

### PR DESCRIPTION
**Pull request by philliphoff**
Adds a skeleton Gulp-based build infrastructure for the project.  This is a prerequisite for moving to TypeScript down the line.  Note that this change keeps the agent and server packages separate but uses a root "pseudo-package" to coordinate NPM installation and build of each packages and sample project.

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Initial glance looks good, will look at it more this afternoon. One thing though, let's set the version numbers at the moment to 0.1. My thinking is that we are well off v1 and we will want our initial releases to be 0.x. We can use a rage on the end of that to denote the build number or release milestone.

**Comment by philliphoff** [comment]
Initial version number isn't a big deal to me; I was just making them consistent.  At the last Node conference I attended there was a big deal made about package versioning starting at 1.0.0 (as opposed to 0.1.0) as it was too easy for 0.x.0 'alpha' releases to become de facto official releases, and that creates havoc with semver.

**Comment by mike-kaufman** [comment]
Any objections to merging this in?

**Comment by jasonyueyang** [comment]
No objection.

**Comment by philliphoff** [comment]
Updated the instructions to mention that the server must (again) be started separately.

**Pull request merged**
