### PR TITLE
Alternate Node module style

### PR DESCRIPTION
**Pull request by joshgav**
Proposing an alternate, more readable style for modules early in our work.

Why the changes?
- Node automatically wraps modules in a closure (see [here](https://github.com/nodejs/node/blob/master/src/node.js#L975-L982)) so we don't need to create one.
- With the closure gone we can return the exported functions directly through `module.exports`.
- It's good to always name functions rather than assign anonymous functions as these names show up in stack traces.
- Always end a text file with `\n` (i.e. newline) (see [here](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)).

### CODE REVIEW

**Comment by avanderhoorn** [comment]
**Scoping/Closures**
Generally speaking I like to encapsulate local variables into modules/code blocks like this. I've found it helps ensure that they are tightly scoped to the specific functionality that they control - even within a single file like this. I've also found that it makes refactoring easier in different scenarios. Lastly, in this specific case, I've put the inspector specific code into the existing closure, if in the future, we need to support other functionality, this might go within other objects outside of this scope. For example:

```
'use strict';

var httpHelper = require('./util/http-helper');
var uuid = require('node-uuid');

// Local only to this module
var support = {
    processRequest: function() {},
    processResponse: function() {},
};

var inspector = (function() {
    // Core state
    var broker = null;
    var sessionCookie = '.Glimpse.Session';
    
    // API Functionality 
    var onBeginRequest = function(req, res) { };
    var onEndRequest = function(req, res) { };
    var init = function(agent) { };
    
    return {
        init: init,
        before: onBeginRequest,
        after: onEndRequest
    }; 
})();

module.exports = inspector;
```  

I think some of this will be mute, as we are going to be moving to typescript/es6 which means we get classes, etc.

**Function Names**
Agreed. Will fix that up.

**Line endings**
I'm used to the IDE doing this automatically. Will fix that up.

**Comment by joshgav** [comment]
Okay cool, my recommendations are based on what I've seen in other modules. Was wondering about our plans to move to ES6; are we concerned about people running earlier versions of Node? Will we babel-ify the libs before publishing?

**Comment by avanderhoorn** [comment]
All great questions. My guess at this point is that we will try and target
back to 0.14 and we have talked about 0.12 given how many projects are
still on that version.

Regardless, we have been talking about using Typescript and that will bring
a some of what we are talking about here to the table. It's just a mater of
getting the build steps in place.

**Comment by joshgav** [comment]
Cool. 4.* is the LTS branch, 5.* is the "stable" branch. 6.* will become the new LTS branch in April. 0.12 and 0.10 should be tested and supported too if possible cause many existing deployments are on them for now, probably till end of CY16.

In order of priority I'd recommend: 4.\*, 5.*, 0.12, 0.10.

**Comment by avanderhoorn** [comment]
Thats fine with me. We should start looking at what our test matrix looks like and what setup we want to use for this.

**Pull request closed without merging**
